{
 "title": "Node Exporteur",
 "description": "dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ROM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  node_filesystem_avail_bytes{mountpoint=\"/\", instance=\"node-exporter:9100\"} \n  / \n  node_filesystem_size_bytes{mountpoint=\"/\", instance=\"node-exporter:9100\"}\n)* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 -  (node_filesystem_avail_bytes{mountpoint=\"/\",instance=\"node-exporter:9100\"} / node_filesystem_size_bytes{mountpoint=\"/\",instance=\"node-exporter:9100\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "update",
   "type": "stat",
   "description": "system update",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"node-exporter:9100\",job=\"node-exporter\"} - node_boot_time_seconds{instance=\"node-exporter:9100\",job=\"node-exporter\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_time_seconds - node_boot_time_seconds) / 3600\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}